version: '3.6'
services:
  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    environment:
      - TZ=Asia/Shanghai
    networks:
      - wms_overlay
    ports:
      - 2181:2181
    volumes:
      - /home/apps/mw/zookeeper/data:/data
    deploy:
      placement:
        constraints:
          - node.labels.zookeeper == zookeeper
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 5s
        monitor: 10s
        max_failure_ratio: 0.1
        order: start-first

networks:
  wms_overlay:
    external: true
